@url = services.unimedbelem.com.br/rest/v1

GET http://repositorio.unimedbelem.com.br/rest/v1/ws_sisaudit_tasy_ligacao/?token=876c9e530d7d449950a13eb53c64f8e9&t=c&qry=U0VMRUNUDQogICAgICAgIENEX1NFVE9SX0FURU5ESU1FTlRPDQogICAgICAgICxj%20YXN0KCBEU19TRVRPUl9BVEVORElNRU5UTyBBUyB2YXJjaGFyMigzMDApIClhcyBT%20RVRPUg0KICAgICAgICBGcm9tIFNFVE9SX0FURU5ESU1FTlRPDQogICAgICAgIHdo%20ZXJlIDE9MQ0KICAgICAgICBhbmQgQ0RfRVNUQUJFTEVDSU1FTlRPID0gMQ0KICAg%20ICAgICBPUkRFUiBCWQ0KICAgICAgICBEU19TRVRPUl9BVEVORElNRU5UTw0KICAg%20ICAgIA==

###
GET http://{{url}}/ws_sisaudit_tasy_ligacao/?token=876c9e530d7d449950a13eb53c64f8e9&t=c&qry=U0VMRUNUDQogICAgICAgIENEX1NFVE9SX0FURU5ESU1FTlRPDQogICAgICAgICxj%20YXN0KCBEU19TRVRPUl9BVEVORElNRU5UTyBBUyB2YXJjaGFyMigzMDApIClhcyBT%20RVRPUg0KICAgICAgICBGcm9tIFNFVE9SX0FURU5ESU1FTlRPDQogICAgICAgIHdo%20ZXJlIDE9MQ0KICAgICAgICBhbmQgQ0RfRVNUQUJFTEVDSU1FTlRPID0gMQ0KICAg%20ICAgICBPUkRFUiBCWQ0KICAgICAgICBEU19TRVRPUl9BVEVORElNRU5UTw0KICAg%20ICAgIA==

###
POST https://{{url}}/ws_sisaudit_tasy_ligacao/
Content-Type: application/json

{
    "token": "876c9e530d7d449950a13eb53c64f8e9",
    "t": "c",
    "qry": "U0VMRUNUDQogICAgICAgIENEX1NFVE9SX0FURU5ESU1FTlRPDQogICAgICAgICxjYXN0KCBEU19TRVRPUl9BVEVORElNRU5UTyBBUyB2YXJjaGFyMigzMDApIClhcyBTRVRPUg0KICAgICAgICBGcm9tIFNFVE9SX0FURU5ESU1FTlRPDQogICAgICAgIHdoZXJlIDE9MQ0KICAgICAgICBhbmQgQ0RfRVNUQUJFTEVDSU1FTlRPID0gMQ0KICAgICAgICBPUkRFUiBCWQ0KICAgICAgICBEU19TRVRPUl9BVEVORElNRU5UTw0KICAg"
}

###

POST https://{{url}}/ws_integracao_sgu_tasy/
Content-Type: multipart/form-data; charset=utf-8; boundary="my boundary"

--my boundary
Content-Disposition: form-data; name="token"

c29saWNpdGFjYW89Nzk4MTc1NTEmZ3VpYT04MDAyMDM0MCZhY2FvPWF0ZW5kaW1lbnRv

--my boundary--

###
POST http://services.unimedbelem.com.br:8080/pacsroutes/getexam
Content-Type: application/json

{
"login":"5344",
"senha":"00105405591",
"token":"876c9e530d7d449950a13eb53c64f8e9"
}

