@url = services.unimedbelem.com.br/rest/v1

REQUISICAO ORIGINAL
### listar consultas ORIGINAL
GET https://repositorio.unimedbelem.com.br/rest/v1/examesconsultar/?token=876c9e530d7d449950a13eb53c64f8e9&baseapi=VGFzeQ==&beneficiario=0880000002754199&_=1645129505085

### NOVO GET listar consultas
GET https://{{url}}/agenda/lista/?token=876c9e530d7d449950a13eb53c64f8e9&baseApi=VGFzeQ==&beneficiario=0880000002754199&_=1645129505085

### NOVO POST JSON
POST https://{{url}}/agenda/lista/
Content-Type: application/json

{
    "token": "876c9e530d7d449950a13eb53c64f8e9",
    "baseApi": "VGFzeQ==",
    "beneficiario": "0880000002754199"
}

### NOVO POST FORM DATA
POST https://{{url}}/agenda/lista/
Content-Type: multipart/form-data; charset=utf-8; boundary="my boundary"

--my boundary
Content-Disposition: form-data; name="token"

876c9e530d7d449950a13eb53c64f8e9v
--my boundary
Content-Disposition: form-data; name="baseApi"

VGFzeQ==
--my boundary
Content-Disposition: form-data; name="beneficiario"

0880000002754199
--my boundary--